### ISSUE TITLE
Receiver host galaxies.mygamesonline.org does not have a valid SSL certificate

### ISSUE THREAD

**Issue by ctya** [devcoin/core#57]
https://www.ssllabs.com/ssltest/analyze.html?d=galaxies.mygamesonline.org

Certificate name mismatch

**Comment by knotwork** [comment]
Umm, I never pretended to have https on there, actually I do not have it on any websites anywhere.

-MarkM-

**Comment by develCuy** [comment]
@knotwork, we need https for security of the network. Can you configure it or another hostname with cloudflare?

**Comment by knotwork** [comment]
I have set up self-signed certificates in the past, though only on servers I actually control; this particular server I am not sure how much control I really have as its a web-hosting provider not an actual dedicated server. Presumably though they must provide some method since https is going to be pushed for heavily soon. I just used to find that the users who actually worried about it usually worried because their browsers complained that the certificate was self-signed not a commercial one that bribed the browser manufacturer so it seemed actually less offputting to users to not bother with https at all.

--MarkM-

**Comment by knotwork** [comment]
OK I can set it up: https://www.google.com/search?client=ubuntu&channel=fs&q=awardspace+set+up+https&ie=utf-8&oe=utf-8

I just need an actual certificate. I believe there might be free ones available nowadays that browsers don't complain about?

-MarkM-

**Comment by develCuy** [comment]
@knotwork you can get one with letsencrypt. You can  also host for free with github pages

**Comment by ctya** [comment]
galaxies.mygamesonline.org has a valid SSL certificate now.
https://www.ssllabs.com/ssltest/analyze.html?d=galaxies.mygamesonline.org
