### ISSUE TITLE
Move all devcoin specific globals (contants & functions) into a single devcoin.h file

### ISSUE THREAD

**Issue by develCuy** [devcoin/core#67]
There are some very specific functions in main.cpp, receiver.h, rpcwallet.cpp and possibly others. Having them all into a file would be very useful, not only for avoiding duplicated code, it will be very helpful when upgrading the codebase to latest stable Bitcoin codebase.

**Comment by ctya** [comment]
A couple of questions about this
Since there is already a receiver.h file, do you mean that should go into a different file?  It is only devcoin functions in receiver.h.

Also, why would we use a new bitcoin base?  How would we decide which BIP to use or not-use?
Why not just continue to improve the current base?

Moving additions to their own file might help.  But what do we do about sections that are deleted from Bitcoin base already?  Do we track what-to-delete in a separate file?

Overall I think this issue assumes we will need to use the latest stable Bitcoin codebase... and that doesn't seem true.  We are making progress to Devcoin version 0.2 as-is so I think we won't need the latest Bitcoin codebase.

**Comment by develCuy** [comment]
@ctya, we were working on updating Devcoin early in this repository, with @sidhujag and @belovachap. The reason is to stay up to date with security updates, given the fact that we are far to have a dedicated security team to audit the code. In short, the strategy is to keep Devcoin core as a living fork of a safe code base. I think that Bitcoin core is the obvious option but we could decide in a separate discussion.

**Comment by develCuy** [comment]
For the new Devcoin Core 22.x I did my best to move as much code as possible to devcoin.h and even devcoin.cpp but didn't liked the result, it only creates bloat for the builder. I prefer to keep code changes as clear as possible, same with commits for future reference.
