### ISSUE TITLE
Solo mining Devcoins on Windows (not supported)

### ISSUE THREAD

**Issue by satoshi0x** [devcoin/core#88]
Hi I was asked to relay this to the GitHub team for a member of our Keybase team.
![01941F9A-0204-497C-9A91-C2A843AFC700](https://user-images.githubusercontent.com/48847567/112814941-69606400-9045-11eb-908c-bc7c1f3f7c56.png)
![4B958740-1FC7-4C27-BEE6-C14A25A5A5B0](https://user-images.githubusercontent.com/48847567/112814945-6a919100-9045-11eb-86dc-80be1e83c0fe.png)

I will direct him here

**Comment by develCuy** [comment]
Thanks for the feedback! If the users is trying solo-mining, we don't support it. The reason is that Devcoin is a merged mined coin, it is not profitable to solo-mine Devcoin because of difficulty design. Rather, we openly and kindly invite people interested on earning Devcoins to join the Devcoin Foundation (DF). You can contact us here: https://keybase.io/team/devcoins
